# Generated by Django 5.1.4 on 2025-01-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developToolList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y%m%d', verbose_name='image')),
                ('ideaContent', models.CharField(max_length=300, verbose_name='아이디어 설명')),
                ('like', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developTool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developmentTool', to='developToolList.developtool', verbose_name='예상 개발툴')),
            ],
        ),
    ]
