# Generated by Django 5.1.4 on 2025-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_ideastar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y%m%d', verbose_name='image'),
        ),
    ]
