# Generated by Django 5.1.4 on 2025-01-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('languageType', models.CharField(max_length=30, verbose_name='종류')),
                ('content', models.CharField(max_length=300, verbose_name='개발툴 설명')),
            ],
        ),
    ]
